contents/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'contents'

urlpatterns = [
    path('feedback/', FeedBackCreate.as_view(), name='feedback_create'),
    path('courses/', CoursesListView.as_view(), name='courses'),
    path('courses/update', update_courses, name='courses'),
    path('courses/relation', CourseRelateCreate.as_view(), name='course_relation'),
    ]

python_test/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static

from contents.views import FrontView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(('provider_oauth.api_urls', 'provider_oauth'), namespace='api')),
    path('oauth/', include(('provider_oauth.urls', 'provider_oauth'), namespace='oauth2')),
    path('profiles/', include(('profiles.urls', 'profiles'), namespace='profiles')),
    path('', include(('contents.urls', 'contents'), namespace='profiles')),
    path('', FrontView.as_view(), name='front'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contents/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

AUTH_USER_MODEL = getattr(settings, 'AUTH_USER_MODEL', 'profiles.User')

class FeedBack(models.Model):
    email = models.EmailField(_('Email address'))
    message = models.TextField(_('Message'))

    def __str__(self):
        return self.email

class Course(models.Model):
    tb_id = models.PositiveIntegerField(_('Course ID'))
    name = models.CharField(_('Course Name'), max_length = 512)
    owner_id = models.PositiveIntegerField(_('Owner ID'))
    content_type = models.PositiveIntegerField()
    owner_name = models.CharField(_('Course developer'), max_length = 256)
    description = models.TextField(_('Description') ,blank = True, null = True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-name']

class CourseRelation(models.Model):
    user_id = models.PositiveIntegerField(_('User ID'))
    # user_id = models.ForeignKey(AUTH_USER_MODEL, on_delete = models.DO_NOTHING)   # Чтобы не тратить время на переделку к ajax
    course_id = models.PositiveIntegerField(_('Course ID'))
    # course_id = models.ForeignKey(Course, on_delete = models.DO_NOTHING)
    session_id = models.PositiveIntegerField(_('Session ID'), blank = True, null = True)

    is_confirm = models.BooleanField(_('Confirmation'), default = False)

    def __str__(self):
        return self.id

    def purchase(self):
        from provider_oauth.api_wrapper import TeachBaseClient as TBClient
        tb_client = TBClient

profiles/forms.py
import django
from django import forms
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.utils.translation import ugettext_lazy as _

from .models import User

email_input_attrs = {}

if django.VERSION >= (1, 11):
    email_input_attrs['autofocus'] = True
elif django.VERSION == (1, 10):
    email_input_attrs['autofocus'] = ''

if django.VERSION >= (1, 9):
    from django.contrib.auth import password_validation
    password_field_kwargs = {'strip': False}
    user_change_form_password_help_text = _(
        "Raw passwords are not stored, so there is no way to see this user's "
        "password, but you can change the password using "
        "<a href=\"../password/\">this form</a>."
    )
    user_creation_form_password2_help_text = _(
        "Enter the same password as before, for verification."
    )
else:
    password_validation = None
    password_field_kwargs = {}
    user_change_form_password_help_text = _(
        "Raw passwords are not stored, so there is no way to see this user's "
        "password, but you can change the password using "
        "<a href=\"password/\">this form</a>."
    )
    user_creation_form_password2_help_text = _(
        "Enter the same password as above, for verification."
    )

password1_field_kwargs = password_field_kwargs.copy()

if django.VERSION >= (1, 11):
    password1_field_kwargs['help_text'] = \
        password_validation.password_validators_help_text_html()


class AuthenticationForm(forms.Form):
    """
    Base class for authenticating users. Extend this to get a form that accepts
    email/password logins.
    """
    email = forms.EmailField(
        label=_("Email address"),
        max_length=254,
        widget=forms.EmailInput(attrs=email_input_attrs),
    )
    password = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput,
        **password_field_kwargs
    )

    error_messages = {
        'invalid_login': _(
            "Please enter a correct %(username)s and password. Note that both "
            "fields may be case-sensitive."
        ),
        'inactive': _("This account is inactive."),
    }

    def __init__(self, request=None, *args, **kwargs):
        """
        The 'request' parameter is set for custom auth use by subclasses.
        The form data comes in via the standard 'data' kwarg.
        """
        self.request = request
        self.user_cache = None
        super(AuthenticationForm, self).__init__(*args, **kwargs)

        UserModel = get_user_model()
        self.username_field = UserModel._meta.get_field(UserModel.USERNAME_FIELD)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email and password:
            if django.VERSION >= (1, 11):
                self.user_cache = authenticate(self.request, email=email, password=password)
            else:
                self.user_cache = authenticate(email=email, password=password)
            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'username': self.username_field.verbose_name},
                )
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def confirm_login_allowed(self, user):
        """
        Controls whether the given User may log in. This is a policy setting,
        independent of end-user authentication. This default behavior is to
        allow login by active users, and reject login by inactive users.

        If the given user cannot log in, this method should raise a
        ``forms.ValidationError``.

        If the given user may log in, this method should return None.
        """
        if not user.is_active:
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )

    def get_user_id(self):
        if self.user_cache:
            return self.user_cache.id
        return None

    def get_user(self):
        return self.user_cache


class UserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given email and
    password.
    """
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    email = forms.EmailField(
        label=_("Email address"),
        max_length=254,
        widget=forms.EmailInput(attrs=email_input_attrs),
    )
    password1 = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput,
        **password1_field_kwargs
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput,
        help_text=user_creation_form_password2_help_text,
        **password_field_kwargs
    )

    class Meta:
        model = User
        fields = []

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        if password_validation:
            self.instance.email = self.cleaned_data.get('email')
            password_validation.validate_password(self.cleaned_data.get('password2'), self.instance)
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    email = forms.EmailField(
        label=_("Email address"),
        max_length=254,
        widget=forms.EmailInput(),
    )
    password = ReadOnlyPasswordHashField(
        label=_("Password"),
        help_text=user_change_form_password_help_text,
    )

    class Meta:
        model = User
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(UserChangeForm, self).__init__(*args, **kwargs)
        f = self.fields.get('user_permissions')
        if f is not None:
            f.queryset = f.queryset.select_related('content_type')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class UserCreateForm(forms.ModelForm):
    class Meta():
        model = User
        fields = ['email', 'first_name']


class PasswordForm(forms.Form):
    password = forms.CharField()
    password_repeat = forms.CharField()

    def clean(self):
        if 'password' in self.cleaned_data and 'password_repeat' in self.cleaned_data:
            if self.cleaned_data['password'] != self.cleaned_data['password_repeat']:
                raise forms.ValidationError(u'Пароли не совпадают')
        return self.cleaned_data

python_test/templates/base.html
<html class='gr__getbootstrap_com'>
<head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://unpkg.com/ionicons@4.4.6/dist/css/ionicons.min.css" rel="stylesheet">
    <!-- Bootstrap CSS -->


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://unpkg.com/ionicons@4.4.6/dist/ionicons.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" ></script>
    <script src="http://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <title>Test TeachBase</title>

</head>
<body class="text-center" data-gr-c-s-loaded="true" style='background-color: #333'>
  <div class="d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="masthead mb-auto">
      <div class="inner">
        <nav class="nav nav-masthead justify-content-center">
          {% if request.user.is_authenticated %}
            <a class="nav-link" href="/courses">Courses</a>
          {% endif %}
          <span class="nav-link">
              {% if request.user.is_authenticated %}
                  Hello {{ request.user.email }},
                  <a href="/profiles/logout">Logout</a>
              {% else %}
                  <a href="/profiles/signin" class="btn btn-primary" %}">Sign-In</a>
                  <a href="/profiles/signup" class="btn btn-dark" %}">Sign-Up</a>

              {% endif %}
          </span>
        </nav>
      </div>
    </header>

    {% block content %}{% endblock content %}


    {% if messages %}
        {% for message in messages %}
        <script type="text/javascript">
          swal("Action!", "{{ message }}", {% if message.tags %}"{{ message.tags }}"{% endif %});
        </script>
        {% endfor %}
    {% endif %}

    <div class="row justify-content-center">
      <div class="col-sm-4">
        <div class="card text-white bg-dark mb-3">
          <div class="card-header">
              FeedBack Form
          </div>
          <form class="form" id='add_feedback' method="POST" action=''>
            <div class="form-group">
              <label for="id_email">Адрес электронной почты:</label>
              <br>
              <input type="email" name="email" maxlength="254" required="" id="id_email">
            </div>
            <div class="form-group ">
              <label for="id_message">Message:</label>
              <br>
              <textarea name="message" cols="40" rows="10" required="" id="id_message"></textarea>
            </div>
            <input type="submit" id='add_feedback_btn' class="btn btn-primary mb-2" value='Add'>
          </form>
        </div>
      </div>

  </div>

  <script type="text/javascript">


    function getCookie(name) {
        var cookieValue = null;
        var i = 0;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (i; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');

   function sendAjaxForm(result_form, ajax_form, url) {
       $.ajax({
           url:     url,
           type:     "POST",
           dataType: "html",
           data: $("#"+ajax_form).serialize(),
           success: function(response) {
            result = $.parseJSON(response);
            swal("Action!", result.message, result.tags);
        },
        error: function(response) {
          console.log(response);
        }
      });
   }

    function csrfSafeMethod(method) {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        crossDomain: false,
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type)) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    $(document).ready(function () {

      $("#add_feedback_btn").click(
        function(){
          sendAjaxForm('result', 'add_feedback', '/feedback/');
          return false;
        }
      );

      $("#add_relation_course_btn").click(
        function(){
          sendAjaxForm('result', 'add_relation_course', '/courses/relation');
          return false;
        }
      );

    });


  </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

python_test/templates/feedback_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register">
  </form>

</body>
</html>

python_test/templates/front.html
{% extends 'base.html'%}

{% block content %}
<main role="main" class="inner cover" style='height: 90%'>

  <h1 style='color: white'>Welcome to TeachBase test platform</h1>

</main>


{% endblock %}